"""3

Revision ID: 0a37398d168c
Revises: 44437ab19903
Create Date: 2019-01-14 15:41:48.922966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a37398d168c'
down_revision = '44437ab19903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('customer', sa.Column('customer_base', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'customer_base')
    op.drop_table('customer_base')
    # ### end Alembic commands ###
