"""agg_

Revision ID: 55ce5224d87b
Revises: dd6bd47afd04
Create Date: 2019-01-15 12:49:07.173173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ce5224d87b'
down_revision = 'dd6bd47afd04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agg_number', sa.Column('numb', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agg_number', 'numb')
    # ### end Alembic commands ###
