"""id1

Revision ID: 855cc6a517ee
Revises: 88ce6a52739e
Create Date: 2019-01-15 16:54:34.237357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855cc6a517ee'
down_revision = '88ce6a52739e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'date')
    # ### end Alembic commands ###
