"""weight cargo

Revision ID: a6cdac3025b2
Revises: cd1fb5ffa137
Create Date: 2019-01-15 07:38:31.868522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6cdac3025b2'
down_revision = 'cd1fb5ffa137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('weigth_cargo', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'weigth_cargo')
    # ### end Alembic commands ###
