"""type of truck

Revision ID: cd1fb5ffa137
Revises: 94cba751c165
Create Date: 2019-01-15 07:28:48.345781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1fb5ffa137'
down_revision = '94cba751c165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('type_of_truck', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'type_of_truck')
    # ### end Alembic commands ###
