"""comments

Revision ID: dd6bd47afd04
Revises: a6cdac3025b2
Create Date: 2019-01-15 07:50:54.513340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6bd47afd04'
down_revision = 'a6cdac3025b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('request_comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'request_comments')
    # ### end Alembic commands ###
